// AUTO-GENERATED by build/extract.py from data.xlsx — do not edit by hand.
// Figures trace to SEDAR+ filings (FY2024–Q3 FY2026). Regenerate: python3 build/extract.py
export const DATA = {
  "company": {
    "name": "First Phosphate Corp.",
    "tickers": [
      "CSE: PHOS",
      "OTCQX: FRSPF",
      "FSE: KD0"
    ],
    "sector": "Critical minerals · LFP battery supply chain",
    "hq": "Saguenay, QC · Vancouver, BC",
    "fyEnd": "February 28/29",
    "stage": "Pre-revenue · exploration–development"
  },
  "asOf": "March 2026",
  "snapshot": {
    "price": 1.05,
    "currency": "C$",
    "marketCap": 158000000,
    "marketCapFD": 202000000,
    "cash": 19983238,
    "cashEst": 32600000,
    "runwayMonths": 24,
    "mktNpv": 0.1,
    "netLossAnnualized": 12700000,
    "sharesOutstanding": 151218841,
    "sharesFD": 192400000,
    "ytdDilution": 1.049,
    "weekRange": "C$0.24 – C$1.13"
  },
  "project": {
    "name": "Bégin-Lamarche",
    "npv": 1590000000,
    "irr": 0.33,
    "capex": 675000000,
    "payback": 2.9,
    "mineLife": 23,
    "production": "1 Mtpa concentrate",
    "resource": 255.5,
    "inferredPct": 0.83,
    "grade": "6.0–8.2% P₂O₅",
    "opex": "US$144/t",
    "royalties": "None (100%-owned)"
  },
  "financials": {
    "periods": [
      "FY2024",
      "FY2025",
      "Q1 FY26",
      "Q2 FY26",
      "Q3 FY26"
    ],
    "periodDates": [
      "Feb 2024",
      "Feb 2025",
      "May 2025",
      "Aug 2025",
      "Nov 2025"
    ],
    "cash": [
      7496238,
      1873550,
      3173855,
      7590632,
      19983238
    ],
    "currentAssets": [
      8972458,
      3692864,
      4972280,
      10919391,
      21333670
    ],
    "totalAssets": [
      12995758,
      7452772,
      8735500,
      14682667,
      25126133
    ],
    "totalLiabilities": [
      3683384,
      1061441,
      568149,
      264229,
      1235289
    ],
    "equity": [
      9312374,
      6391331,
      8167351,
      14418438,
      23890844
    ],
    "accumDeficit": [
      -21947674,
      -29575088,
      -31323426,
      -33329435,
      -39107263
    ],
    "sharesOutstanding": [
      73786772,
      89947551,
      97023899,
      123546512,
      151218841
    ],
    "netLoss": [
      -8292468,
      -7627414,
      -1748338,
      -2006005,
      -5777828
    ],
    "totalExpenses": [
      -8599172,
      -8528149,
      -2025236,
      -2254057,
      -5798152
    ],
    "bookValuePerShare": [
      0.126207,
      0.071056,
      0.084179,
      0.116705,
      0.157989
    ],
    "currentRatio": [
      2.435928,
      3.479104,
      8.751718,
      41.325483,
      17.270185
    ],
    "debtToEquity": [
      0.395537,
      0.166075,
      0.069563,
      0.018326,
      0.051706
    ],
    "cashPctAssets": [
      0.576822,
      0.25139,
      0.363328,
      0.516979,
      0.795317
    ],
    "expenseBreakdownFY2025": [
      {
        "label": "Exploration & metallurgy",
        "value": 3939800
      },
      {
        "label": "Share-based comp",
        "value": 2496911
      },
      {
        "label": "Business development",
        "value": 677042
      },
      {
        "label": "R&D / consulting",
        "value": 538237
      },
      {
        "label": "Professional fees",
        "value": 480361
      },
      {
        "label": "General & admin",
        "value": 224686
      },
      {
        "label": "Regulatory",
        "value": 161112
      },
      {
        "label": "Management fees",
        "value": 10000
      }
    ]
  },
  "burn": {
    "quarters": [
      "Q4 FY24",
      "Q1 FY25",
      "Q2 FY25",
      "Q3 FY25",
      "Q4 FY25",
      "Q1 FY26",
      "Q2 FY26",
      "Q3 FY26"
    ],
    "netLoss": [
      -3764747,
      -4185217,
      -170997,
      -1681986,
      -1589214,
      -1748338,
      -2006009,
      -5777828
    ],
    "cashBalance": [
      7496238,
      1651673,
      410444,
      149983,
      1873550,
      3173855,
      7590632,
      19983238
    ],
    "sharesOutstanding": [
      73786772,
      74867570,
      76103368,
      77198802,
      89947551,
      97023899,
      123546512,
      151218841
    ],
    "cumulativeDilution": [
      0,
      0.014648,
      0.031396,
      0.046242,
      0.21902,
      0.314923,
      0.674372,
      1.049403
    ]
  },
  "runway": {
    "estCashJan2026": 32600000,
    "scenarios": [
      {
        "name": "Bull",
        "qBurn": 2500000,
        "months": 39.1,
        "note": "lower burn holds"
      },
      {
        "name": "Base",
        "qBurn": 3200000,
        "months": 30.6,
        "note": "current trajectory"
      },
      {
        "name": "Bear",
        "qBurn": 4500000,
        "months": 21.7,
        "note": "full drill ramp"
      }
    ]
  },
  "capexGap": {
    "items": [
      {
        "label": "Bégin-Lamarche mine (PEA)",
        "value": 675000000,
        "status": "Needs FS → financing"
      },
      {
        "label": "Phosphoric-acid facility",
        "value": 240000000,
        "status": "Pre-FS complete"
      },
      {
        "label": "First Saguenay pCAM plant",
        "value": 90000000,
        "status": "FS complete"
      }
    ],
    "totalRequired": 1005000000,
    "currentCash": 32600000,
    "twoYearBurn": 21400000,
    "availableForCapex": 11200000,
    "fundingGap": 993800000
  },
  "peers": {
    "navDiscount": [
      {
        "ticker": "PHOS",
        "name": "First Phosphate",
        "mktNpv": 0.1,
        "self": true
      },
      {
        "ticker": "LCE",
        "name": "Century Lithium",
        "mktNpv": 0.04
      },
      {
        "ticker": "DAN",
        "name": "Arianne Phosphate",
        "mktNpv": 0.025
      },
      {
        "ticker": "NMG",
        "name": "Nouveau Monde",
        "mktNpv": 0.34
      },
      {
        "ticker": "PMET",
        "name": "PMET Resources",
        "mktNpv": 0.37
      }
    ],
    "irr": [
      {
        "ticker": "PHOS",
        "name": "First Phosphate",
        "irr": 0.33,
        "self": true
      },
      {
        "ticker": "LCE",
        "name": "Century Lithium",
        "irr": 0.274
      },
      {
        "ticker": "NMG",
        "name": "Nouveau Monde",
        "irr": 0.2
      },
      {
        "ticker": "DAN",
        "name": "Arianne Phosphate",
        "irr": 0.187
      },
      {
        "ticker": "PMET",
        "name": "PMET Resources",
        "irr": 0.181
      }
    ],
    "table": [
      {
        "ticker": "PHOS",
        "name": "First Phosphate",
        "component": "Phosphate → cathode",
        "stage": "PEA (2024)",
        "mktCap": "C$158M",
        "npv": "C$1,590M",
        "irr": "33%",
        "capex": "C$675M",
        "mktNpv": "0.10×",
        "self": true
      },
      {
        "ticker": "DAN",
        "name": "Arianne Phosphate",
        "component": "Phosphate (concentrate)",
        "stage": "FS (2013)",
        "mktCap": "C$55M",
        "npv": "C$2,200M",
        "irr": "18.7%",
        "capex": "C$1,200M",
        "mktNpv": "0.025×"
      },
      {
        "ticker": "NMG",
        "name": "Nouveau Monde",
        "component": "Graphite → anode",
        "stage": "Pre-construction",
        "mktCap": "US$344M",
        "npv": "~US$1B",
        "irr": "~20%",
        "capex": "~C$1B+",
        "mktNpv": "0.34×"
      },
      {
        "ticker": "PMET",
        "name": "PMET Resources",
        "component": "Lithium → cathode",
        "stage": "FS (2025)",
        "mktCap": "C$584M",
        "npv": "C$1,594M",
        "irr": "18.1%",
        "capex": "C$2,600M",
        "mktNpv": "0.37×"
      },
      {
        "ticker": "LCE",
        "name": "Century Lithium",
        "component": "Lithium → cathode",
        "stage": "FS (2026)",
        "mktCap": "C$106M",
        "npv": "~US$3B",
        "irr": "27.4%",
        "capex": "~US$1B",
        "mktNpv": "0.04×"
      }
    ]
  },
  "valuation": {
    "npv": 1590000000,
    "currentPrice": 1.05,
    "sharesBasic": 173267217,
    "sharesFD": 192400000,
    "sensitivityPct": [
      0.03,
      0.05,
      0.07,
      0.1,
      0.11,
      0.15,
      0.2,
      0.25
    ],
    "impliedBasic": [
      0.275297,
      0.458829,
      0.64236,
      0.917658,
      1.009423,
      1.376487,
      1.835315,
      2.294144
    ],
    "impliedFD": [
      0.247921,
      0.413202,
      0.578482,
      0.826403,
      0.909044,
      1.239605,
      1.652807,
      2.066008
    ],
    "scenarios": [
      {
        "name": "Bear",
        "pct": 0.03,
        "price": 0.275,
        "label": "PEA-stage, 83% Inferred",
        "rationale": "Typical PEA-stage explorer discount; speculative resource."
      },
      {
        "name": "Base",
        "pct": 0.11,
        "price": 1.009,
        "label": "Where PHOS trades",
        "rationale": "Current market — LFP premium already in the price.",
        "current": true
      },
      {
        "name": "Bull",
        "pct": 0.2,
        "price": 1.835,
        "label": "FS complete, de-risked",
        "rationale": "Post-FS, financing secured, clearer path to production."
      },
      {
        "name": "Moon",
        "pct": 0.35,
        "price": 3.212,
        "label": "Construction / FID",
        "rationale": "FID made, construction underway, major dilution factored in."
      }
    ]
  },
  "thesis": {
    "bull": [
      "The only pure-play LFP-phosphate company on North American exchanges — no direct comparable.",
      "Already produced commercial-grade LFP 18650 cells: proof of the mine-to-battery chain.",
      "Strong government backing — C$16.7M federal grant plus critical-mineral tax credits.",
      "PEA shows a 33% after-tax IRR and 2.9-year payback — best-in-class among junior peers.",
      "LFP reached ~50% of EV battery chemistry in 2024; phosphate is the supply-constrained node."
    ],
    "base": [
      "Trades at ~10% of PEA NAV — a premium to phosphate juniors, a discount to LFP-chain peers.",
      "Well-funded near term (~C$33M, ~24-month runway) but pre-revenue until ~2029.",
      "Re-rating hinges on near-term catalysts: drill results → PFS → financing.",
      "LFP optionality is the whole premium — fertilizer economics are the floor."
    ],
    "bear": [
      "83% of the resource is Inferred — speculative until a feasibility study confirms it.",
      "A C$675M+ initial-capex gap with no committed financing path.",
      "105%+ share dilution since FY2024, with more required to fund development.",
      "Going-concern audit opinion; no revenue for years.",
      "PEA assumptions may not survive a feasibility study."
    ]
  },
  "catalysts": [
    {
      "date": "Mar 2026",
      "event": "C$16.7M non-repayable federal contribution",
      "weight": "major",
      "note": "Government validation; narrows the capex gap."
    },
    {
      "date": "Feb 2026",
      "event": "Phosphate added to Canada's critical-minerals list",
      "weight": "major",
      "note": "Unlocks 30% CMETC + critical-mineral tax credits."
    },
    {
      "date": "Feb 2026",
      "event": "ADR program launched (OTCQX: FPHOY)",
      "weight": "minor",
      "note": "Broader US institutional access."
    },
    {
      "date": "Jan 2026",
      "event": "Initial offtake-agreement payment received",
      "weight": "minor",
      "note": "First commercial-revenue milestone."
    },
    {
      "date": "Dec 2025",
      "event": "Added to the CSE25 Index",
      "weight": "minor",
      "note": "Passive-fund visibility."
    },
    {
      "date": "Dec 2025",
      "event": "C$9.6M financing closed",
      "weight": "minor",
      "note": "Extended runway."
    },
    {
      "date": "Jul 2025",
      "event": "Commercial-grade LFP 18650 cells produced",
      "weight": "major",
      "note": "Mine-to-battery proof of concept."
    }
  ],
  "forwardCatalysts": [
    {
      "window": "Q1–Q2 2026",
      "event": "30,000 m drill-program results",
      "impact": "Resource upgrade: Inferred → Indicated"
    },
    {
      "window": "2026",
      "event": "Pre-Feasibility Study initiation",
      "impact": "Major de-risking event"
    },
    {
      "window": "2026–27",
      "event": "Strategic JV / partnership for capex",
      "impact": "De-risks the funding gap"
    },
    {
      "window": "2027+",
      "event": "Feasibility Study completion",
      "impact": "Unlocks project finance; NAV re-rate"
    }
  ],
  "risks": [
    {
      "factor": "Capex funding failure",
      "severity": "Critical",
      "probability": "Medium",
      "mitigation": "Govt grants, JV potential",
      "sev": 4,
      "prob": 2
    },
    {
      "factor": "Continued dilution",
      "severity": "High",
      "probability": "High",
      "mitigation": "None — inherent to the model",
      "sev": 3,
      "prob": 3
    },
    {
      "factor": "Resource downgrade in PFS/FS",
      "severity": "High",
      "probability": "Medium",
      "mitigation": "30,000 m drill program underway",
      "sev": 3,
      "prob": 2
    },
    {
      "factor": "Permitting delays",
      "severity": "Medium",
      "probability": "Medium",
      "mitigation": "QC mining-friendly; critical mineral",
      "sev": 2,
      "prob": 2
    },
    {
      "factor": "LFP chemistry shift",
      "severity": "Medium",
      "probability": "Low",
      "mitigation": "LFP gaining share; fertilizer fallback",
      "sev": 2,
      "prob": 1
    }
  ],
  "governance": {
    "ratings": [
      {
        "area": "Technical expertise",
        "stars": 5
      },
      {
        "area": "Strategic relationships",
        "stars": 5
      },
      {
        "area": "Compensation alignment",
        "stars": 5
      },
      {
        "area": "Insider conviction",
        "stars": 5
      },
      {
        "area": "Executive leadership",
        "stars": 4
      },
      {
        "area": "Board independence",
        "stars": 3
      },
      {
        "area": "Operational readiness",
        "stars": 3
      }
    ],
    "overall": 4,
    "highlights": [
      {
        "k": "CEO compensation",
        "v": "100% equity, C$0 cash",
        "note": "Maximum alignment — the CEO only wins if the share price does."
      },
      {
        "k": "CEO open-market buying",
        "v": "~C$1.8M",
        "note": "2.87M shares bought with personal capital since May 2023."
      },
      {
        "k": "CEO ownership",
        "v": "~17.3%",
        "note": "Largest individual shareholder; also a key-man risk."
      },
      {
        "k": "Board alignment",
        "v": "100% RSU fees",
        "note": "Directors paid entirely in equity since Sep 2023."
      }
    ],
    "insiders": [
      {
        "name": "John Passalacqua",
        "role": "CEO & Director",
        "bought": "2,872,000 sh (~C$1.8M)"
      },
      {
        "name": "Peter Nicholson",
        "role": "Independent Director",
        "bought": "532,000 sh (C$146K)"
      },
      {
        "name": "Laurence Zeifman",
        "role": "Chairman",
        "bought": "359,500 sh (C$74K)"
      }
    ]
  },
  "projectDetail": {
    "summary": "Bégin-Lamarche is an igneous (anorthosite-hosted) phosphate project in the Saguenay–Lac-St-Jean region of Québec. Its 2024 PEA outlines a 23-year, 1 Mtpa concentrate operation feeding a downstream purified-phosphoric-acid and LFP-cathode strategy — the basis of the mine-to-battery thesis.",
    "economics": [
      {
        "k": "After-tax NPV (8%)",
        "v": "C$1,590M"
      },
      {
        "k": "After-tax IRR",
        "v": "33%"
      },
      {
        "k": "Initial capex",
        "v": "C$675M"
      },
      {
        "k": "Payback",
        "v": "2.9 years"
      },
      {
        "k": "Mine life",
        "v": "23 years"
      },
      {
        "k": "Production",
        "v": "1 Mtpa concentrate"
      },
      {
        "k": "Operating cost",
        "v": "US$144 / t conc."
      },
      {
        "k": "Revenue at production",
        "v": "~C$600M / yr"
      },
      {
        "k": "Royalties",
        "v": "None (100%-owned)"
      },
      {
        "k": "Land position",
        "v": "~1,500 km² claims"
      }
    ],
    "resource": {
      "total": 255.5,
      "grade": "6.0–8.2% P₂O₅",
      "split": [
        {
          "label": "Inferred",
          "pct": 0.83,
          "note": "speculative — needs FS"
        },
        {
          "label": "Measured + Indicated",
          "pct": 0.17,
          "note": "higher confidence"
        }
      ]
    },
    "downstream": [
      {
        "step": "Mine & concentrator",
        "detail": "Igneous phosphate → high-purity concentrate",
        "capex": "C$675M",
        "status": "PEA"
      },
      {
        "step": "Purified phosphoric acid",
        "detail": "Battery-grade PPA (low-contaminant)",
        "capex": "C$240M",
        "status": "Pre-FS"
      },
      {
        "step": "pCAM / LFP cathode",
        "detail": "First Saguenay cathode-active-material plant",
        "capex": "C$90M",
        "status": "FS complete"
      },
      {
        "step": "LFP cells",
        "detail": "Commercial-grade 18650 cells demonstrated (Jul 2025)",
        "capex": "—",
        "status": "Proven"
      }
    ]
  },
  "market": {
    "lfpShareEV": 0.5,
    "lfpShare2022": 0.37,
    "chinaLfpPowder": 0.9,
    "phosphatePrice": "~US$600 / t (DAP/MAP)",
    "marketGrowth": {
      "years": [
        "2024",
        "2027",
        "2030",
        "2032"
      ],
      "low": [
        17,
        30,
        48,
        64
      ],
      "high": [
        17,
        38,
        62,
        84
      ],
      "cagr": "17–19%"
    },
    "drivers": [
      {
        "k": "EV adoption",
        "v": "LFP overtook NMC to ~50% of EV chemistry in 2024",
        "note": "Cost & safety favour LFP for mass-market EVs."
      },
      {
        "k": "Grid storage (ESS)",
        "v": "ESS demand +50% YoY (J.P. Morgan)",
        "note": "LFP dominates stationary storage."
      },
      {
        "k": "Supply concentration",
        "v": "China ~90% of LFP powder",
        "note": "Western supply chains seek non-China phosphate."
      },
      {
        "k": "Critical-mineral policy",
        "v": "Phosphate listed US (Nov 2025) & Canada (Feb 2026)",
        "note": "Unlocks tax credits & fast-track permitting."
      }
    ]
  },
  "supplyChain": {
    "chain": [
      "Phosphate rock",
      "Concentrate",
      "Purified phosphoric acid",
      "pCAM",
      "LFP cathode",
      "LFP cell"
    ],
    "phosNode": 2,
    "cluster": [
      {
        "ticker": "PHOS",
        "input": "Phosphate",
        "self": true
      },
      {
        "ticker": "NMG",
        "input": "Graphite (anode)"
      },
      {
        "ticker": "PMET",
        "input": "Lithium (cathode)"
      }
    ],
    "insight": "Three of the four North-American LFP-input juniors are Québec-based (PHOS phosphate, NMG graphite, PMET lithium), creating a natural cluster for government support and logistics. PHOS has already produced commercial LFP 18650 cells using its own phosphate and NMG graphite — the only junior in the group to demonstrate the full mine-to-battery chain."
  },
  "capital": {
    "sharesBasic": 151218841,
    "sharesCurrent": 173267217,
    "sharesFD": 192400000,
    "omnibusReservedPct": 0.096,
    "omnibusCapPct": 0.2,
    "debt": "Debt-free (FT premium only)",
    "financingMethod": "Flow-through + placements",
    "ownership": [
      {
        "name": "John Passalacqua (CEO)",
        "pct": 0.173
      },
      {
        "name": "L. Zeifman (Chairman)",
        "pct": 0.061
      },
      {
        "name": "B. Kurtz (CFO)",
        "pct": 0.054
      },
      {
        "name": "P. Nicholson (Director)",
        "pct": 0.028
      },
      {
        "name": "Other insiders / float",
        "pct": 0.684
      }
    ]
  },
  "financing": [
    {
      "date": "Mar 2026",
      "item": "C$16.7M non-repayable federal contribution",
      "type": "Non-dilutive",
      "note": "Conditional; narrows the capex gap."
    },
    {
      "date": "Feb 2026",
      "item": "Critical-mineral designation (Canada)",
      "type": "Tax credits",
      "note": "30% CMETC + critical-mineral tax credits."
    },
    {
      "date": "Dec 2025",
      "item": "C$9.6M financing closed",
      "type": "Equity",
      "note": "Extended runway to mid-2027."
    },
    {
      "date": "FY2026",
      "item": "Flow-through share placements",
      "type": "Equity (tax-advantaged)",
      "note": "Primary funding method; drives dilution."
    },
    {
      "date": "Future",
      "item": "Project finance / JV for capex",
      "type": "Debt / strategic",
      "note": "Required to close the ~C$994M gap."
    }
  ],
  "esg": [
    {
      "area": "Indigenous relations",
      "rating": 5,
      "detail": "President Armand MacKenzie helped draft the UN Declaration on the Rights of Indigenous Peoples; leading a partnership with the Pekuakamiulnuatsh First Nation for deep Indigenous financial participation."
    },
    {
      "area": "Permitting jurisdiction",
      "rating": 4,
      "detail": "Québec is consistently ranked among the most mining-friendly jurisdictions; phosphate's critical-mineral status supports fast-tracking."
    },
    {
      "area": "Resource ownership",
      "rating": 5,
      "detail": "100%-owned claims (~1,500 km²) with no royalties — clean title and full upside retention."
    },
    {
      "area": "Community / local roots",
      "rating": 4,
      "detail": "SVP David Dufour brings 30+ years of Saguenay operating and community experience; local social licence is a strategic priority."
    },
    {
      "area": "Governance independence",
      "rating": 3,
      "detail": "Only 2 of 5 directors are independent — below TSXV best practice; a key-man dependency on the CEO."
    }
  ],
  "comps": {
    "pnav": [
      {
        "ticker": "PHOS",
        "v": 0.1,
        "self": true
      },
      {
        "ticker": "DAN",
        "v": 0.025
      },
      {
        "ticker": "LCE",
        "v": 0.04
      },
      {
        "ticker": "NMG",
        "v": 0.34
      },
      {
        "ticker": "PMET",
        "v": 0.37
      }
    ],
    "evResource": [
      {
        "ticker": "PHOS",
        "v": 0.62,
        "self": true
      },
      {
        "ticker": "DAN",
        "v": 0.09
      }
    ],
    "footballField": [
      {
        "method": "PEA-NAV (bear–bull)",
        "low": 0.28,
        "high": 1.83,
        "mid": 1.01,
        "note": "3% → 20% of after-tax NPV"
      },
      {
        "method": "Peer P/NAV re-rate",
        "low": 0.92,
        "high": 2.29,
        "mid": 1.38,
        "note": "to junior-peer 10–25% of NAV"
      },
      {
        "method": "EV / resource (vs DAN)",
        "low": 0.45,
        "high": 1.38,
        "mid": 0.92,
        "note": "5–15% of NPV per tonne"
      },
      {
        "method": "Upside (post-FS / FID)",
        "low": 1.83,
        "high": 3.21,
        "mid": 2.52,
        "note": "de-risked → construction",
        "upside": true
      }
    ],
    "fairValueLow": 0.28,
    "fairValueHigh": 1.83
  },
  "roadmap": [
    {
      "phase": "PEA",
      "when": "2024",
      "done": true,
      "detail": "NPV C$1.59B · IRR 33% established"
    },
    {
      "phase": "30,000 m drill program",
      "when": "2026",
      "done": false,
      "detail": "Upgrade Inferred → Indicated resource"
    },
    {
      "phase": "Pre-Feasibility Study",
      "when": "2026",
      "done": false,
      "detail": "First major de-risking"
    },
    {
      "phase": "Feasibility Study",
      "when": "2027",
      "done": false,
      "detail": "Bankable economics → project finance"
    },
    {
      "phase": "Financing / FID",
      "when": "2027–28",
      "done": false,
      "detail": "Debt · JV · strategic · equity"
    },
    {
      "phase": "Construction",
      "when": "2028",
      "done": false,
      "detail": "Mine + downstream build-out"
    },
    {
      "phase": "First production",
      "when": "~2029",
      "done": false,
      "detail": "Concentrate → revenue"
    }
  ],
  "advisory": [
    {
      "name": "Yves Caprara",
      "role": "Phosphoric-acid technology",
      "stars": 5,
      "note": "Former CEO of Prayon SA — Europe's largest food/technical phosphoric-acid producer. The single most relevant advisor to the PPA thesis."
    },
    {
      "name": "Bernard Lapointe, PhD",
      "role": "Québec phosphate",
      "stars": 5,
      "note": "Founded Arianne Phosphate (the only other significant Québec phosphate company); proved phosphate viability in Saguenay–Lac-St-Jean."
    },
    {
      "name": "Gary Stanley",
      "role": "US critical-minerals policy",
      "stars": 5,
      "note": "Former Director, Office of Critical Minerals & Metals, US Dept. of Commerce; lead author of the 2019 US Critical Minerals Strategy."
    },
    {
      "name": "Mario Bouchard",
      "role": "Québec government finance",
      "stars": 5,
      "note": "Former Assistant Deputy Minister for Strategic Industries — insider knowledge of provincial project financing, critical for the capex."
    },
    {
      "name": "Dr. Peir Pufahl, P.Geo",
      "role": "Phosphorite geology",
      "stars": 4,
      "note": "Queen's University professor; internationally recognised phosphorite expert partnered with PHOS on its mineralogy."
    }
  ],
  "glossary": [
    {
      "t": "PEA",
      "d": "Preliminary Economic Assessment — the earliest, least-certain economic study of a mining project."
    },
    {
      "t": "PFS / FS",
      "d": "Pre-Feasibility / Feasibility Study — progressively more rigorous, bankable studies."
    },
    {
      "t": "NI 43-101",
      "d": "Canadian standard for disclosing mineral resources/reserves; classes are Inferred, Indicated, Measured."
    },
    {
      "t": "Inferred resource",
      "d": "Lowest-confidence resource class — cannot be used in a feasibility study or reserves."
    },
    {
      "t": "NAV / NPV",
      "d": "Net asset value / net present value — the discounted value of a project's future cash flows."
    },
    {
      "t": "IRR",
      "d": "Internal rate of return — the discount rate at which a project's NPV is zero."
    },
    {
      "t": "LFP",
      "d": "Lithium iron phosphate — a low-cost, safe battery cathode chemistry (Li-Fe-PO₄)."
    },
    {
      "t": "PPA",
      "d": "Purified phosphoric acid — battery-grade input for cathode-active material."
    },
    {
      "t": "pCAM / CAM",
      "d": "(precursor) cathode-active material — the processed feed for battery cathodes."
    },
    {
      "t": "Flow-through shares",
      "d": "A Canadian tax-advantaged financing where exploration expenses pass through to investors."
    },
    {
      "t": "CMETC",
      "d": "Critical Mineral Exploration Tax Credit — a 30% Canadian credit for eligible critical-mineral work."
    },
    {
      "t": "P₂O₅",
      "d": "Phosphorus pentoxide — the standard measure of phosphate grade/content."
    }
  ],
  "coverage": {
    "assessment": "High-risk / high-reward — speculative",
    "fairValueLow": 0.28,
    "fairValueHigh": 1.83,
    "staticPrice": 1.05,
    "stats": [
      {
        "k": "Mkt cap",
        "v": "C$158M"
      },
      {
        "k": "Mkt cap / NAV",
        "v": "~10%"
      },
      {
        "k": "PEA NPV",
        "v": "C$1.59B"
      },
      {
        "k": "PEA IRR",
        "v": "33%"
      },
      {
        "k": "Cash runway",
        "v": "~24 mo"
      },
      {
        "k": "Stage",
        "v": "PEA · pre-revenue"
      }
    ]
  },
  "monitoring": [
    {
      "metric": "Quarterly cash balance",
      "current": "C$20.0M (Q3)",
      "watch": "Below C$10M"
    },
    {
      "metric": "Shares outstanding",
      "current": "~173M",
      "watch": "Above 200M"
    },
    {
      "metric": "Mkt cap / NAV",
      "current": "~10%",
      "watch": ">15% rich · <5% distress"
    },
    {
      "metric": "Resource classification",
      "current": "83% Inferred",
      "watch": "Upgrade → Indicated"
    },
    {
      "metric": "LFP share of EV batteries",
      "current": "~50%",
      "watch": "Shift back to NMC"
    },
    {
      "metric": "Phosphate price (DAP/MAP)",
      "current": "~US$600/t",
      "watch": "Rising = positive"
    }
  ],
  "vintage": {
    "filings": "SEDAR+ filings through Q3 FY2026 (Nov 30, 2025)",
    "market": "Peer & market data as of March 2026",
    "price": "Share price live (15-min delayed) when available; else C$1.05 (Mar 2026)"
  },
  "sources": [
    "FY2024 & FY2025 audited annual financial statements (SEDAR+)",
    "Q1–Q3 FY2026 interim financial statements (SEDAR+)",
    "Management Discussion & Analysis, Q1–Q3 FY2026",
    "Peer & market data from public sources (Mar 2026)"
  ]
};
export default DATA;
