// AUTO-GENERATED by build/extract.py from data.xlsx — do not edit by hand.
// Figures trace to SEDAR+ filings (FY2024–Q3 FY2026). Regenerate: python3 build/extract.py
export const DATA = {
  "company": {
    "name": "First Phosphate Corp.",
    "tickers": [
      "CSE: PHOS",
      "OTCQX: FRSPF",
      "FSE: KD0"
    ],
    "sector": "Critical minerals · LFP battery supply chain",
    "hq": "Saguenay, QC · Vancouver, BC",
    "fyEnd": "February 28/29",
    "stage": "Pre-revenue · exploration–development"
  },
  "asOf": "March 2026",
  "snapshot": {
    "price": 1.05,
    "currency": "C$",
    "marketCap": 158000000,
    "marketCapFD": 202000000,
    "cash": 19983238,
    "cashEst": 32600000,
    "runwayMonths": 24,
    "mktNpv": 0.1,
    "netLossAnnualized": 12700000,
    "sharesOutstanding": 151218841,
    "sharesFD": 192400000,
    "ytdDilution": 1.049,
    "weekRange": "C$0.24 – C$1.13"
  },
  "project": {
    "name": "Bégin-Lamarche",
    "npv": 1590000000,
    "irr": 0.33,
    "capex": 675000000,
    "payback": 2.9,
    "mineLife": 23,
    "production": "1 Mtpa concentrate",
    "resource": 255.5,
    "inferredPct": 0.83,
    "grade": "6.0–8.2% P₂O₅",
    "opex": "US$144/t",
    "royalties": "None (100%-owned)"
  },
  "financials": {
    "periods": [
      "FY2024",
      "FY2025",
      "Q1 FY26",
      "Q2 FY26",
      "Q3 FY26"
    ],
    "periodDates": [
      "Feb 2024",
      "Feb 2025",
      "May 2025",
      "Aug 2025",
      "Nov 2025"
    ],
    "cash": [
      7496238,
      1873550,
      3173855,
      7590632,
      19983238
    ],
    "currentAssets": [
      8972458,
      3692864,
      4972280,
      10919391,
      21333670
    ],
    "totalAssets": [
      12995758,
      7452772,
      8735500,
      14682667,
      25126133
    ],
    "totalLiabilities": [
      3683384,
      1061441,
      568149,
      264229,
      1235289
    ],
    "equity": [
      9312374,
      6391331,
      8167351,
      14418438,
      23890844
    ],
    "accumDeficit": [
      -21947674,
      -29575088,
      -31323426,
      -33329435,
      -39107263
    ],
    "sharesOutstanding": [
      73786772,
      89947551,
      97023899,
      123546512,
      151218841
    ],
    "netLoss": [
      -8292468,
      -7627414,
      -1748338,
      -2006005,
      -5777828
    ],
    "totalExpenses": [
      -8599172,
      -8528149,
      -2025236,
      -2254057,
      -5798152
    ],
    "bookValuePerShare": [
      0.126207,
      0.071056,
      0.084179,
      0.116705,
      0.157989
    ],
    "currentRatio": [
      2.435928,
      3.479104,
      8.751718,
      41.325483,
      17.270185
    ],
    "debtToEquity": [
      0.395537,
      0.166075,
      0.069563,
      0.018326,
      0.051706
    ],
    "cashPctAssets": [
      0.576822,
      0.25139,
      0.363328,
      0.516979,
      0.795317
    ],
    "expenseBreakdownFY2025": [
      {
        "label": "Exploration & metallurgy",
        "value": 3939800
      },
      {
        "label": "Share-based comp",
        "value": 2496911
      },
      {
        "label": "Business development",
        "value": 677042
      },
      {
        "label": "R&D / consulting",
        "value": 538237
      },
      {
        "label": "Professional fees",
        "value": 480361
      },
      {
        "label": "General & admin",
        "value": 224686
      },
      {
        "label": "Regulatory",
        "value": 161112
      },
      {
        "label": "Management fees",
        "value": 10000
      }
    ]
  },
  "burn": {
    "quarters": [
      "Q4 FY24",
      "Q1 FY25",
      "Q2 FY25",
      "Q3 FY25",
      "Q4 FY25",
      "Q1 FY26",
      "Q2 FY26",
      "Q3 FY26"
    ],
    "netLoss": [
      -3764747,
      -4185217,
      -170997,
      -1681986,
      -1589214,
      -1748338,
      -2006009,
      -5777828
    ],
    "cashBalance": [
      7496238,
      1651673,
      410444,
      149983,
      1873550,
      3173855,
      7590632,
      19983238
    ],
    "sharesOutstanding": [
      73786772,
      74867570,
      76103368,
      77198802,
      89947551,
      97023899,
      123546512,
      151218841
    ],
    "cumulativeDilution": [
      0,
      0.014648,
      0.031396,
      0.046242,
      0.21902,
      0.314923,
      0.674372,
      1.049403
    ]
  },
  "runway": {
    "estCashJan2026": 32600000,
    "scenarios": [
      {
        "name": "Bull",
        "qBurn": 2500000,
        "months": 39.1,
        "note": "lower burn holds"
      },
      {
        "name": "Base",
        "qBurn": 3200000,
        "months": 30.6,
        "note": "current trajectory"
      },
      {
        "name": "Bear",
        "qBurn": 4500000,
        "months": 21.7,
        "note": "full drill ramp"
      }
    ]
  },
  "capexGap": {
    "items": [
      {
        "label": "Bégin-Lamarche mine (PEA)",
        "value": 675000000,
        "status": "Needs FS → financing"
      },
      {
        "label": "Phosphoric-acid facility",
        "value": 240000000,
        "status": "Pre-FS complete"
      },
      {
        "label": "First Saguenay pCAM plant",
        "value": 90000000,
        "status": "FS complete"
      }
    ],
    "totalRequired": 1005000000,
    "currentCash": 32600000,
    "twoYearBurn": 21400000,
    "availableForCapex": 11200000,
    "fundingGap": 993800000
  },
  "peers": {
    "navDiscount": [
      {
        "ticker": "PHOS",
        "name": "First Phosphate",
        "mktNpv": 0.1,
        "self": true
      },
      {
        "ticker": "LCE",
        "name": "Century Lithium",
        "mktNpv": 0.04
      },
      {
        "ticker": "DAN",
        "name": "Arianne Phosphate",
        "mktNpv": 0.025
      },
      {
        "ticker": "NMG",
        "name": "Nouveau Monde",
        "mktNpv": 0.34
      },
      {
        "ticker": "PMET",
        "name": "PMET Resources",
        "mktNpv": 0.37
      }
    ],
    "irr": [
      {
        "ticker": "PHOS",
        "name": "First Phosphate",
        "irr": 0.33,
        "self": true
      },
      {
        "ticker": "LCE",
        "name": "Century Lithium",
        "irr": 0.274
      },
      {
        "ticker": "NMG",
        "name": "Nouveau Monde",
        "irr": 0.2
      },
      {
        "ticker": "DAN",
        "name": "Arianne Phosphate",
        "irr": 0.187
      },
      {
        "ticker": "PMET",
        "name": "PMET Resources",
        "irr": 0.181
      }
    ],
    "table": [
      {
        "ticker": "PHOS",
        "name": "First Phosphate",
        "component": "Phosphate → cathode",
        "stage": "PEA (2024)",
        "mktCap": "C$158M",
        "npv": "C$1,590M",
        "irr": "33%",
        "capex": "C$675M",
        "mktNpv": "0.10×",
        "self": true
      },
      {
        "ticker": "DAN",
        "name": "Arianne Phosphate",
        "component": "Phosphate (concentrate)",
        "stage": "FS (2013)",
        "mktCap": "C$55M",
        "npv": "C$2,200M",
        "irr": "18.7%",
        "capex": "C$1,200M",
        "mktNpv": "0.025×"
      },
      {
        "ticker": "NMG",
        "name": "Nouveau Monde",
        "component": "Graphite → anode",
        "stage": "Pre-construction",
        "mktCap": "US$344M",
        "npv": "~US$1B",
        "irr": "~20%",
        "capex": "~C$1B+",
        "mktNpv": "0.34×"
      },
      {
        "ticker": "PMET",
        "name": "PMET Resources",
        "component": "Lithium → cathode",
        "stage": "FS (2025)",
        "mktCap": "C$584M",
        "npv": "C$1,594M",
        "irr": "18.1%",
        "capex": "C$2,600M",
        "mktNpv": "0.37×"
      },
      {
        "ticker": "LCE",
        "name": "Century Lithium",
        "component": "Lithium → cathode",
        "stage": "FS (2026)",
        "mktCap": "C$106M",
        "npv": "~US$3B",
        "irr": "27.4%",
        "capex": "~US$1B",
        "mktNpv": "0.04×"
      }
    ]
  },
  "valuation": {
    "npv": 1590000000,
    "currentPrice": 1.05,
    "sharesBasic": 173267217,
    "sharesFD": 192400000,
    "sensitivityPct": [
      0.03,
      0.05,
      0.07,
      0.1,
      0.11,
      0.15,
      0.2,
      0.25
    ],
    "impliedBasic": [
      0.275297,
      0.458829,
      0.64236,
      0.917658,
      1.009423,
      1.376487,
      1.835315,
      2.294144
    ],
    "impliedFD": [
      0.247921,
      0.413202,
      0.578482,
      0.826403,
      0.909044,
      1.239605,
      1.652807,
      2.066008
    ],
    "scenarios": [
      {
        "name": "Bear",
        "pct": 0.03,
        "price": 0.275,
        "label": "PEA-stage, 83% Inferred",
        "rationale": "Typical PEA-stage explorer discount; speculative resource."
      },
      {
        "name": "Base",
        "pct": 0.11,
        "price": 1.009,
        "label": "Where PHOS trades",
        "rationale": "Current market — LFP premium already in the price.",
        "current": true
      },
      {
        "name": "Bull",
        "pct": 0.2,
        "price": 1.835,
        "label": "FS complete, de-risked",
        "rationale": "Post-FS, financing secured, clearer path to production."
      },
      {
        "name": "Moon",
        "pct": 0.35,
        "price": 3.212,
        "label": "Construction / FID",
        "rationale": "FID made, construction underway, major dilution factored in."
      }
    ]
  },
  "thesis": {
    "bull": [
      "The only pure-play LFP-phosphate company on North American exchanges — no direct comparable.",
      "Already produced commercial-grade LFP 18650 cells: proof of the mine-to-battery chain.",
      "Strong government backing — C$16.7M federal grant plus critical-mineral tax credits.",
      "PEA shows a 33% after-tax IRR and 2.9-year payback — best-in-class among junior peers.",
      "LFP reached ~50% of EV battery chemistry in 2024; phosphate is the supply-constrained node."
    ],
    "base": [
      "Trades at ~10% of PEA NAV — a premium to phosphate juniors, a discount to LFP-chain peers.",
      "Well-funded near term (~C$33M, ~24-month runway) but pre-revenue until ~2029.",
      "Re-rating hinges on near-term catalysts: drill results → PFS → financing.",
      "LFP optionality is the whole premium — fertilizer economics are the floor."
    ],
    "bear": [
      "83% of the resource is Inferred — speculative until a feasibility study confirms it.",
      "A C$675M+ initial-capex gap with no committed financing path.",
      "105%+ share dilution since FY2024, with more required to fund development.",
      "Going-concern audit opinion; no revenue for years.",
      "PEA assumptions may not survive a feasibility study."
    ]
  },
  "catalysts": [
    {
      "date": "Mar 2026",
      "event": "C$16.7M non-repayable federal contribution",
      "weight": "major",
      "note": "Government validation; narrows the capex gap."
    },
    {
      "date": "Feb 2026",
      "event": "Phosphate added to Canada's critical-minerals list",
      "weight": "major",
      "note": "Unlocks 30% CMETC + critical-mineral tax credits."
    },
    {
      "date": "Feb 2026",
      "event": "ADR program launched (OTCQX: FPHOY)",
      "weight": "minor",
      "note": "Broader US institutional access."
    },
    {
      "date": "Jan 2026",
      "event": "Initial offtake-agreement payment received",
      "weight": "minor",
      "note": "First commercial-revenue milestone."
    },
    {
      "date": "Dec 2025",
      "event": "Added to the CSE25 Index",
      "weight": "minor",
      "note": "Passive-fund visibility."
    },
    {
      "date": "Dec 2025",
      "event": "C$9.6M financing closed",
      "weight": "minor",
      "note": "Extended runway."
    },
    {
      "date": "Jul 2025",
      "event": "Commercial-grade LFP 18650 cells produced",
      "weight": "major",
      "note": "Mine-to-battery proof of concept."
    }
  ],
  "forwardCatalysts": [
    {
      "window": "Q1–Q2 2026",
      "event": "30,000 m drill-program results",
      "impact": "Resource upgrade: Inferred → Indicated"
    },
    {
      "window": "2026",
      "event": "Pre-Feasibility Study initiation",
      "impact": "Major de-risking event"
    },
    {
      "window": "2026–27",
      "event": "Strategic JV / partnership for capex",
      "impact": "De-risks the funding gap"
    },
    {
      "window": "2027+",
      "event": "Feasibility Study completion",
      "impact": "Unlocks project finance; NAV re-rate"
    }
  ],
  "risks": [
    {
      "factor": "Capex funding failure",
      "severity": "Critical",
      "probability": "Medium",
      "mitigation": "Govt grants, JV potential",
      "sev": 4,
      "prob": 2
    },
    {
      "factor": "Continued dilution",
      "severity": "High",
      "probability": "High",
      "mitigation": "None — inherent to the model",
      "sev": 3,
      "prob": 3
    },
    {
      "factor": "Resource downgrade in PFS/FS",
      "severity": "High",
      "probability": "Medium",
      "mitigation": "30,000 m drill program underway",
      "sev": 3,
      "prob": 2
    },
    {
      "factor": "Permitting delays",
      "severity": "Medium",
      "probability": "Medium",
      "mitigation": "QC mining-friendly; critical mineral",
      "sev": 2,
      "prob": 2
    },
    {
      "factor": "LFP chemistry shift",
      "severity": "Medium",
      "probability": "Low",
      "mitigation": "LFP gaining share; fertilizer fallback",
      "sev": 2,
      "prob": 1
    }
  ],
  "governance": {
    "ratings": [
      {
        "area": "Technical expertise",
        "stars": 5
      },
      {
        "area": "Strategic relationships",
        "stars": 5
      },
      {
        "area": "Compensation alignment",
        "stars": 5
      },
      {
        "area": "Insider conviction",
        "stars": 5
      },
      {
        "area": "Executive leadership",
        "stars": 4
      },
      {
        "area": "Board independence",
        "stars": 3
      },
      {
        "area": "Operational readiness",
        "stars": 3
      }
    ],
    "overall": 4,
    "highlights": [
      {
        "k": "CEO compensation",
        "v": "100% equity, C$0 cash",
        "note": "Maximum alignment — the CEO only wins if the share price does."
      },
      {
        "k": "CEO open-market buying",
        "v": "~C$1.8M",
        "note": "2.87M shares bought with personal capital since May 2023."
      },
      {
        "k": "CEO ownership",
        "v": "~17.3%",
        "note": "Largest individual shareholder; also a key-man risk."
      },
      {
        "k": "Board alignment",
        "v": "100% RSU fees",
        "note": "Directors paid entirely in equity since Sep 2023."
      }
    ],
    "insiders": [
      {
        "name": "John Passalacqua",
        "role": "CEO & Director",
        "bought": "2,872,000 sh (~C$1.8M)"
      },
      {
        "name": "Peter Nicholson",
        "role": "Independent Director",
        "bought": "532,000 sh (C$146K)"
      },
      {
        "name": "Laurence Zeifman",
        "role": "Chairman",
        "bought": "359,500 sh (C$74K)"
      }
    ]
  },
  "sources": [
    "FY2024 & FY2025 audited annual financial statements (SEDAR+)",
    "Q1–Q3 FY2026 interim financial statements (SEDAR+)",
    "Management Discussion & Analysis, Q1–Q3 FY2026",
    "Peer & market data from public sources (Mar 2026)"
  ]
};
export default DATA;
